Repository gitpod-io/gitbot, pull requests merged in 2021-11, with the labels that each got.

#50 [deploy-labeler] Add deployed label immediately
  plugins/deployed-labeler/main.go
Labels: approved, size/XS, lgtm, release-note

#48 [projectmanager] handle PRs the same as issues
  config/plugins.yaml
  plugins/projectmanager/main.go
Labels: approved, lgtm, size/M, release-note-none

#54 Update container image dependencies
  .gitpod.Dockerfile
Labels: approved, size/S, lgtm, release-note-none

#56 Update OWNERS to contain Platform team
  OWNERS
Labels: approved, size/XS, lgtm, release-note-none

#55 Use GH review status instead of labels for tide query
  config/config.yaml
Labels: approved, size/XS, lgtm, release-note-none
